version: '2'
services:
  db:
    container_name: db
    image: pitisec/postgresql-9.4-plv8
    volumes:
      - ./_db:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - "5432:5432"
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - front
  dns:
    image: robmadole/devdns
    container_name: dns
    ports:
      - "5300:5300/udp"
    environment:
      ANSWER: "127.0.0.1"
    networks:
        - front
networks:
  front:
    driver: bridge
  back:
    driver: bridge