version: '2'
services:
  db93:
    container_name: db93
    image: pitisec/postgresql-9.3-plv8
    volumes:
      - ./_db93:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - "5433:5432"
  db94:
    container_name: db94
    image: pitisec/postgresql-9.4-plv8
    volumes:
      - ./_db94:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - "5434:5432"
  db95:
    container_name: db95
    image: pitisec/postgresql-9.5-plv8
    volumes:
      - ./_db95:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - "5435:5432"
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - front
  dns:
    image: robmadole/devdns
    container_name: dns
    ports:
      - "5300:5300/udp"
    environment:
      ANSWER: "127.0.0.1"
    networks:
        - front
networks:
  front:
    driver: bridge
  back:
    driver: bridge